Made array arguments `readonly`.
Testy/TestyTs pull request #78
Opened 2021-07-05 16:19 UTC by geon

The array arguments have no business being mutable.

## Purpose

The assertion functions can't be called with ReadonlyArray<T>. That is bad.

## Approach

Make the arguments `readonly`.

## Learnings

https://www.typescriptlang.org/docs/handbook/interfaces.html#readonly-properties

2021-07-07 15:49 UTC, Aboisier requested changes
Thanks for your contribution!

Would you mind adding tests in order to document your use cases and prevent potential regressions?

There are already a few tests [here](https://github.com/Testy/TestyTs/blob/main/src/spec/assertion/arraysToBeEqual.spec.ts) and [here](https://github.com/Testy/TestyTs/blob/main/src/spec/assertion/toBeIn.spec.ts).

2021-07-09 10:31 UTC, geon commented
@Aboisier 

I don't know how I could add tests for this. The change affects only the typing. It has no runtime impact.

A test of this would have to involve running the compiler on invalid code and see if it gives the correct error. Probably outside the scope of this project.

2021-07-11 01:04 UTC, Aboisier commented
@geon 

Indeed, the test would simply prevent accidental changes to the interface.

2021-07-11 21:12 UTC, Aboisier approved these changes
LGTM!

2021-07-11 21:13 UTC, merged

2021-07-12 12:10 UTC, Aboisier commented
This has now been published in the latest version,1.5.0. Thanks for your contribution, it is really appreciated!